# Generated by Django 3.2.7 on 2021-10-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='proprietario',
            field=models.IntegerField(null=True),
        ),
    ]
